---
title: книги
---
привет, я Паша Любецкий. другой сайт с творчеством -- <https://abalompe.gitlab.io/>.

# Суфийские мотивы

__адрес:__ <https://reuptake.github.io/sufi>

Стихи и проза с суфийскими мотивами.

Одно из стихотворений -- [перевод на белорусский язык](https://reuptake.github.io/sufi/translations.html#rumi) стихотворения поэта-суфия [Джалаладдина Руми](https://ru.wikipedia.org/wiki/%D0%94%D0%B6%D0%B0%D0%BB%D0%B0%D0%BB%D0%B0%D0%B4%D0%B4%D0%B8%D0%BD_%D0%A0%D1%83%D0%BC%D0%B8).

> Правобраз у кожнай рэчы ёсць,  
> аснова па-за намі.  
> Яе не знішчаць гнеў і злосць,  
> не здзьме яе вірамі.
>
> Згасае водсвет, не святло.  
> Жыцця крыніцы ззянне  
> б’е ў сутнасць, бы прамень у шкло  
> люстэрка існавання.
>
> _<...>_

# образы (книга без иллюстраций)

__адрес:__ <https://reuptake.github.io/visual>

книга состоит из визуальных образов, которые можно нарисовать, но иллюстраций в ней нет.

__примеры:__

- дружелюбная, на скромная бездночка: очень стесняется, когда в неё всматриваются, у неё краснеют от этого щёки.
- портал в мир, где нет речи и словесного мышления. только солнце, звёзды и тишина.
- призраки погибших вселенных и угасших звёзд, у которых остались незаконченные дела.
- норковые шубы, вылазящие из своих нор и собирающиеся на охоту.
- норковые мыслекрады (такие маленькие существа, которые воруют мысли у тебя из-под носа и коллекционируют потом у себя в норках).
- мыслепуты (существа, запутывающие мысли, помещающие мысли в путы).
- путешествие между реальностями через белый шум различных телеканалов.
- песочные часы, в которых сыпется прах умирающего времени.
- навозные жуки, перекатывающие планеты из навоза по их орбитам.
- гибриды нетбуков и котов: сами себя вылизывают (не нужно чистить от пыли) и засыпают на коленях.
- старая чёрно-белая фотография огромного зала, где сидят десятки женщин-вычислительниц и вычисляют на бумаге хэши для майнинга первых биткоинов.
- идеяла (сотканные из идей одеяла, которыми можно укрыться с головой от холодной и страшной реальности).
- элементарные частицы, которые очень любят, когда им чешут спины.

# черновики за 2010-2018 годы

__адрес:__ <https://reuptake.github.io/drafts>

Черновики за 2010-2018 годы.

__Источники:__

- <https://web.archive.org/web/20180715042459/https://reuptake.github.io/>
- <https://web.archive.org/web/20171213223512/https://reuptake.github.io/>
- <https://web.archive.org/web/20170311131254/http://reuptake.github.io/art/poems-interesting.html>
